---
name: precommit-update

on:
  workflow_dispatch:
  # Run monthly
  schedule:
    - cron: 0 2 1 * *

permissions:
  contents: read

env:
  GITLEAKS_VERSION: 8.28.0

jobs:
  precommit:
    name: precommit-update
    runs-on: ubuntu-latest
    # To create PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Install gitleaks
        run: |
          cd /tmp/
          curl -sSfLO https://github.com/gitleaks/gitleaks/releases/download/v$GITLEAKS_VERSION/gitleaks_$GITLEAKS_VERSION_linux_x64.tar.gz
          tar xzf gitleaks_*_linux_x64.tar.gz
          sudo install -m 755 gitleaks /usr/local/bin/
        continue-on-error: true
      - name: Install trufflehog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
        continue-on-error: true
      - name: Run pre-commit
        run: pre-commit run -a
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725  # v8.0.0
        with:
          title: "ci(pre-commit): autoupdate"
          commit-message: "Automatic pre-commit update"
          branch: "precommit-update"
